blog_writing_task:
  description: >
    The task is to write a well researched blog on the topic: {topic}.
    The blog should always contain:
    1. Fun facts about the topic :{topic}.
    2. Emoji's wherever applicable.
    3. Real life analogies wherever need may be.
    4. Fun and easy to understand the writing style.

    The Blog should be fun to read by youngsters and increses the reader's counts.
    The Blog should be review when written.


    Tasks to be Done.
    1. Research on {topic} by researcher.
    2. Writing blog as per the requiements of the writer.
    3. Reviewing the blog at the end and giving feedback by the blog reviewer.
 
  
  expected_output: >
    Blog should be save as the markdown file to the given path.
    the blog should be well structured and be able to display the Emoji's added 
    inside the content of the blog.

