summarization_task:
  description: >
    Understant the user query: {query}
    Do the proper research from the information available and list down the facts and summarize
    them in proper markdown structure, do not know the answer of query, you reply with i do not know
    and you do not give the made up answer and try not to hallucinate at best.
  expected_output: >
    List of summarize fact about query: {query} in proper markdown format.

  agent: research_summarization
  
  markdown: true




